name: Build and Profile using Docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-profile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Install linux-tools on host
      #   run: |
      #     KERNEL_VERSION=$(uname -r)
      #     sudo apt-get update && sudo apt-get install -y \
      #       linux-tools-common linux-tools-generic \
      #       linux-tools-azure linux-cloud-tools-azure \
      #       linux-tools-$KERNEL_VERSION linux-cloud-tools-$KERNEL_VERSION \
      #       linux-tools-6.8.0-1020-azure \
      #       linux-cloud-tools-6.8.0-1020-azure \
      #       linux-tools-azure \
      #       linux-cloud-tools-azure || true

      - name: Run the Docker container and execute the profiling script
        run: |
          docker run --privileged -u $(id -u):$(id -g) -v $(pwd):/host adiprerepa/598ape /bin/bash -c "
            cd /host &&
            make -j &&
            perf record -F 99 -g -- ./main.exe -i inputs/pianoroom.ray --ppm -o output/pianoroom.ppm -H 500 -W 500 &&
            perf stat -o perfstat.txt -- ./main.exe -i inputs/pianoroom.ray --ppm -o output/pianoroom.ppm -H 500 -W 500 &&
            chown $(id -u):$(id -g) perf.data &&
            perf script | perl FlameGraph/stackcollapse-perf.pl | perl FlameGraph/flamegraph.pl --width 2400 --height 48 > flamegraph.svg"

      - name: Upload profiling artifacts
        uses: actions/upload-artifact@v4
        with:
          name: profiling-results
          path: |
            perf.data
            perfstat.txt
            flamegraph.svg
